on: workflow_dispatch
name: 🚀 Deploy Website
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Get latest code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build website
      run: npm run build

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        protocol: ftps
        local-dir: ./dist/